####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-tpsa
Description: Simulators and utilities for automatic differentiation
Version: 2026.04-pre
Label: 2026.04-pre
Maintainer: svtv@norceresearch.no
MaintainerName: Svenn Tveit
Url: http://opm-project.org
Depends: dune-istl (>= 2.9) opm-common opm-grid opm-simulators
